import arrShuffle from '@/modules/arrShuffle'
import type { RecommendedVideo } from '@/types'
import { VideoTag } from '@/types'

const recommendedVideos: RecommendedVideo[] = arrShuffle([
    {
        title: 'Factory Pattern - Object Oriented PHP Tutorial',
        link: 'https://youtu.be/H5lor4wyl1Y',
        img: 'object-oriented-php-tutorial.jpg',
        date: '2019-12-02',
        tags: [VideoTag.All],
    },
    {
        title: 'Php Objects & Static Methods (Object Oriented Php 2020)',
        link: 'https://youtu.be/_Zd9B_jUwlw',
        img: 'objects-and-static-methods.jpg',
        date: '2020-01-20',
        tags: [VideoTag.All],
    },
    {
        title: 'Building a PHP Framework ep1: The dependency injection container',
        link: 'https://youtu.be/8bfuR6nEpwY',
        img: 'the-dependency-injection-container.jpg',
        date: '2018-05-22',
        tags: [VideoTag.All],
    },
    {
        title: 'Marco Pivetta – From helpers to middleware',
        link: 'https://youtu.be/MjpiHy_e8kQ',
        img: 'from-helpers-to-middleware.jpg',
        date: '2019-12-05',
        tags: [VideoTag.All],
    },
    {
        title: 'PHP UK Conference 2018 - Kat Zien - Performance optimisation: how do I go about it?',
        link: 'https://youtu.be/4hB7tGcz1l8',
        img: 'performance-optimisation-how-do-I-go-about-it.jpg',
        date: '2018-03-29',
        tags: [VideoTag.All],
    },
    {
        title: 'Test to Break Principles - Rob Waller - PHP UK Conference 2019',
        link: 'https://youtu.be/JDwFyRXbVHQ',
        img: 'test-to-break-principles-rob-waller.jpg',
        date: '2019-03-20',
        tags: [VideoTag.All],
    },
    {
        title: 'PHP Solid Principles ~ Lesson 1: Single Responsibility',
        link: 'https://youtu.be/ARxZV8OZ8Cg',
        img: 'php-solid-principles-single-responsibility.jpg',
        date: '2019-12-03',
        tags: [VideoTag.All],
    },
    {
        title: 'Top 100 PHP Functions ( 1 - 10 ) | Learn PHP Programming',
        link: 'https://youtu.be/t9FrpTZm1ds',
        img: 'top-100-php-functions-1-10.jpg',
        date: '2018-11-19',
        tags: [VideoTag.All],
    },
    {
        title: 'What Is Object-Oriented Programming?',
        link: 'https://youtu.be/3rrnnbz-mY8',
        img: 'What-Is-Object-Oriented-Programming.jpg',
        date: '2018-04-06',
        tags: [VideoTag.All],
    },
    {
        title: 'Controlling the Variables - Thijs Feryn - PHP UK Conference 2019',
        link: 'https://youtu.be/f3EU-sd9KPY',
        img: 'controlling-the-variables.jpg',
        date: '2019-03-19',
        tags: [VideoTag.All],
    },
    {
        title: 'PHP UK Conference 2018 - Mark Niebergall -Debugging PHP with Xdebug',
        link: 'https://youtu.be/4wkHBwkhu7g',
        img: 'PHP-UK-Conference-2018-Mark-Niebergall-Debugging-PHP-with-Xdebug.jpg',
        date: '2018-03-29',
        tags: [VideoTag.All],
    },
    {
        title: 'Functional Programming in PHP',
        link: 'https://youtu.be/LZh4_q04aKo',
        img: 'Functional-Programming-in-PHP.jpg',
        date: '2018-10-05',
        tags: [VideoTag.All],
    },
    {
        title: 'PHP REST API From Scratch [1] - Database & Read',
        link: 'https://youtu.be/OEWXbpUMODk',
        img: 'PHP-REST-API-From-Scratch-1-Database-Read.jpg',
        date: '2018-05-27',
        tags: [VideoTag.All],
    },
    {
        title: 'Authentication With Slim 4 (Lesson 1: Setup Slim)',
        link: 'https://youtu.be/3Hg2WPwDyG8',
        img: 'Authentication-With-Slim-4-Lesson-1-Setup-Slim.jpg',
        date: '2020-02-17',
        tags: [VideoTag.All],
    },
    {
        title: 'PHP UK Conference 2017 - Gareth Ellis - Introduction to SOLID',
        link: 'https://youtu.be/86Tt2pW9pv4',
        img: 'PHP-UK-Conference-2017-Gareth Ellis-Introduction-to-SOLID.jpg',
        date: '2017-04-03',
        tags: [VideoTag.All],
    },
    {
        title: '#devbreak19 - 25 Years of PHP',
        link: 'https://youtu.be/80ysU2Xl4Zk',
        img: 'devbreak19-25-Years-of-PHP.jpg',
        date: '2019-08-07',
        tags: [VideoTag.All],
    },
    {
        title: '25 years of PHP - Rasmus Lerdorf',
        link: 'https://youtu.be/nmD1Q4FsXCc',
        img: '25-years-of-PHP-Rasmus-Lerdorf-video.jpg',
        date: '2019-07-11',
        tags: [VideoTag.All],
    },
    {
        title: 'What is Class in PHP - OOP Tutorial - in 5 Minutes',
        link: 'https://youtu.be/pObVzQjRWtg',
        img: 'What-is-Class-in-PHP-OOP-Tutorial-in-5-Minutes.jpg',
        date: '2020-04-03',
        tags: [VideoTag.All],
    },
    {
        title: 'Object Oriented programming in PHP | PHP for Beginners - Part 20',
        link: 'https://youtu.be/cNe_24n3maY',
        img: 'Object-Oriented-programming-in-PHP.jpg',
        date: '2020-04-16',
        tags: [VideoTag.All],
    },
    {
        title: 'Serverless PHP applications with Bref - Matthiew Napoli - PHP UK 2020',
        link: 'https://youtu.be/R2V4QTM2aes',
        img: 'Serverless-PHP-applications-with-Bre-Matthiew-Napoli-PHP-UK-2020.jpg',
        date: '2020-03-12',
        tags: [VideoTag.All],
    },
    {
        title: "What's new in PHP 8.0",
        link: 'https://youtu.be/uU1-ZqIbYes',
        img: 'Whats-new-in-PHP-8-0.webp',
        date: '2020-11-28',
        tags: [VideoTag.All],
    },
    {
        title: 'Laravel Crash Course 2020',
        link: 'https://youtu.be/MFh0Fd7BsjE',
        img: 'Laravel-Crash-Course-2020.webp',
        date: '2020-11-16',
        tags: [VideoTag.All, VideoTag.Laravel],
    },
    {
        title: '5 Exciting New Features in PHP 8.1',
        link: 'https://youtu.be/T8QZkpVvDxc',
        img: '5-Exciting-New-Features-in-PHP-81.webp',
        date: '2021-10-12',
        tags: [VideoTag.All],
    },
    {
        title: "What's New in PHP 8.1: Enums, First-Class Callables, Fibers, Readonly Properties, and More",
        link: 'https://youtu.be/rgrQSmUiFJQ',
        img: 'Whats-New-in-PHP-81-Enums-First-Class-Callables-Fibers-Readonly-Properties-and-More.webp',
        date: '2021-11-25',
        tags: [VideoTag.All],
    },
    {
        title: 'Unit Testing with PHP Unit',
        link: 'https://youtu.be/a5ZKCFINUkU',
        img: 'Unit-Testing-with-PHP-Unit.webp',
        date: '2021-03-07',
        tags: [VideoTag.All],
    },
    {
        title: 'PHP Unit Testing with PHPUnit | Automated PHP Testing Tutorial [2021]',
        link: 'https://youtu.be/kkU43JdJQBE',
        img: 'PHP-Unit-Testing-with-PHPUnit-Automated-PHP-Testing-Tutorial-2021.webp',
        date: '2021-05-10',
        tags: [VideoTag.All],
    },
    {
        title: '5 Reasons to Use PHP 8: New Syntax Features',
        link: 'https://youtu.be/F-AWT88vsyM',
        img: '5-Reasons-to-Use-PHP-8-New-Syntax-Features.webp',
        date: '2021-11-05',
        tags: [VideoTag.All],
    },
    {
        title: 'The Future of PHP',
        link: 'https://www.youtube.com/watch?v=wuJ2W3n0vXg',
        img: 'The-Future-of-PHP.webp',
        date: '2022-08-04',
        tags: [VideoTag.All],
    },
    {
        title: 'Why use PHP in 2022?',
        link: 'https://www.youtube.com/watch?v=X5lxnlcjrWM',
        img: 'Why-use-PHP-in-2022.webp',
        date: '2022-06-15',
        tags: [VideoTag.All],
    },
    {
        title: 'The evolution of PHP',
        link: 'https://www.youtube.com/watch?v=x9bSUo6TGgY',
        img: 'From-PHP-5-6-to-PHP-8-2.webp',
        date: '2022-07-17',
        tags: [VideoTag.All],
    },
    {
        title: 'Celebrating PHP 8.3',
        link: 'https://www.youtube.com/live/VWryF035B6U?si=HzqFkcaMdIBgGlVa',
        img: 'Celebrating-PHP-8-3.webp',
        date: '2023-11-23',
        tags: [VideoTag.All],
    },
    {
        title: 'Breaking changes in PHP 8.3!',
        link: 'https://youtu.be/mGf_ShkSdmE?si=EBC9q0RDM5gIvLBR',
        img: 'Breaking-changes-in-PHP-8-3.webp',
        date: '2023-10-26',
        tags: [VideoTag.All],
    },
    {
        title: 'PHP For Beginners - Complete Laracasts Course',
        link: 'https://youtu.be/fw5ObX8P6as?si=L7E6jf4UNTNOxLy1',
        img: 'PHP-For-Beginners-Complete-Laracasts-Course.webp',
        date: '2023-11-21',
        tags: [VideoTag.All],
    },
    {
        title: 'In Defence of PHP - Stephen Rees-Carter - NDC Security 2023',
        link: 'https://youtu.be/zlPBufBzscg?si=7yYQlVjPl5A-ej7N',
        img: 'In-Defence-of-PHP-Stephen-Rees-Carter-NDC-Security-2023.webp',
        date: '2023-04-20',
        tags: [VideoTag.All],
    },
    {
        title: "Readonly clones, #[Override], and json_validate: what's new in PHP 8.3",
        link: 'https://youtu.be/nJFsD0bnlTI?si=Y51fxIQFM3C91CTZ',
        img: 'Readonly-clones-and-json_validate-whats-new-in-PHP-8-3.webp',
        date: '2023-10-05',
        tags: [VideoTag.All],
    },
    {
        title: `"Developing Symfony applications in 2023" [eng] / Nicolas Grekas`,
        link: 'https://youtu.be/EwAVP3BoNOg?si=zTioUaqULIyZsMdH',
        img: 'Developing-Symfony-applications-in-2023-Nicolas-Grekas.webp',
        date: '2023-11-24',
        tags: [VideoTag.All, VideoTag.Symfony],
    },
    {
        title: 'Is PHP 8.3 adding types to class constants?!',
        link: 'https://youtu.be/E8lbWznz1d0?si=OWZMOXmR-MmIvjo5',
        img: 'Is-PHP-8-3-adding-types-to-class-constants.webp',
        date: '2023-10-13',
        tags: [VideoTag.All],
    },
    {
        title: 'Clean your controller with Laravel prepareForValidation method',
        link: 'https://youtu.be/RbMlMAULJm8?si=lj_ExcBmAeKgIkMs',
        img: 'Clean your controller with Laravel prepareForValidation method.webp',
        date: '2022-09-24',
        tags: [VideoTag.All, VideoTag.Laravel],
    },
    {
        title: 'Logging Unique Views in Laravel with Redis: Playing with Redis sets and HyperLogLog (1/4)',
        link: 'https://youtu.be/FGLDa3e4ZGM?si=Z4_l2wqn09oPViiI',
        img: 'Logging Unique Views in Laravel with Redis- Playing with Redis sets and HyperLogLog (1-4).webp',
        date: '2024-02-20',
        tags: [VideoTag.All, VideoTag.Laravel],
    },
    {
        title: 'Up And Running with Pest: Introduction and demo (01/35)',
        link: 'https://youtu.be/jyfoHw05Mbw?si=8VfLZqiwmJPf1TQ6',
        img: 'Up And Running with Pest- Introduction and demo (01-35).webp',
        date: '2022-03-28',
        tags: [VideoTag.All],
    },
    {
        title: "What's New in PHP 8.3 - Derick Rethans",
        link: 'https://youtu.be/3U0DGhzSH2U?si=x6EHaR5jvJmorgV0',
        img: "What's New in PHP 8.3 - Derick Rethans.webp",
        date: '2024-02-22',
        tags: [VideoTag.All],
    },
    {
        title: 'Boosting Frontend Speed: Quick Wins for Backend Developers - Paul Conroy',
        link: 'https://youtu.be/BZuWGil_7kY?si=zqeyIP2afbIrT2ts',
        img: 'Boosting Frontend Speed- Quick Wins for Backend Developers - Paul Conroy.webp',
        date: '2024-02-21',
        tags: [VideoTag.All],
    },
    {
        title: 'PHP is the future',
        link: 'https://youtu.be/xmvD_EjNE-4?si=iu_8S-Imzwd-jPqf',
        img: 'PHP is the future.webp',
        date: '2023-05-12',
        tags: [VideoTag.All],
    },
    {
        title: 'Jr. Devs: Want More Opportunities? Learn PHP!',
        link: 'https://youtu.be/0ysPpAr3-w4?si=BbcQYnPOvDkCQgiE',
        img: 'JrDevs Want More Opportunities Learn PHP.webp',
        date: '2024-04-08',
        tags: [VideoTag.All],
    },
    {
        title: 'Learn Object Oriented PHP for Beginners | OOP PHP Tutorial',
        link: 'https://youtu.be/yrFr5PMdk2A?si=A2JP_ytKYSTLyRnZ',
        img: 'Learn Object Oriented PHP for Beginners OOP PHP Tutorial.webp',
        date: '2023-08-30',
        tags: [VideoTag.All],
    },
    {
        title: 'No more Docker for PHP',
        link: 'https://youtu.be/sY2A6AGF5os?si=HD5uSN0YbnUPVJq0',
        img: 'No more Docker for PHP.webp',
        date: '2023-10-13',
        tags: [VideoTag.All],
    },
    {
        title: 'How to run PHP for Nginx with PHP-FPM using Docker and docker-compose',
        link: 'https://youtu.be/TswVrfNQZHc?si=zO0wqsmkUpQaHOL4',
        img: 'How to run PHP for Nginx with PHP-FPM using Docker and docker-compose.webp',
        date: '2024-02-19',
        tags: [VideoTag.All],
    },
    {
        title: 'Running PHP 1.0 in 2024',
        link: 'https://youtu.be/0BPExYh5Anw?si=SqWEZ2ah5ri2ObHF',
        img: 'Running PHP 1-0 in 2024.webp',
        date: '2024-06-10',
        tags: [VideoTag.All],
    },
    {
        title: 'Benchmarking Laravel with Swoole, FrankenPHP, RoadRunner, php-fpm, and ngx-php',
        link: 'https://youtu.be/ZB129Tjkas8?si=nIfMp362_Pg5KTCR',
        img: 'Benchmarking Laravel with Swoole FrankenPHP RoadRunner php-fpm and ngx-php.webp',
        date: '2024-08-06',
        tags: [VideoTag.All, VideoTag.Laravel],
    },
    {
        title: 'Why I use final',
        link: 'https://youtu.be/HiD6CwWq5Ds?si=la-SRbQWBLZAXOe5&t=1175',
        img: 'Why I use final.webp',
        date: '2024-08-08',
        tags: [VideoTag.All],
    },
    {
        title: 'Laravel First Impressions From A JavaScript Dev',
        link: 'https://youtu.be/Spwv0RbITmE?si=QjjYtPHTCUfo51bi',
        img: 'Laravel First Impressions From A JavaScript Dev.webp',
        date: '2023-05-22',
        tags: [VideoTag.All, VideoTag.Laravel],
    },
    {
        title: 'PHP Full Course for non-haters',
        link: 'https://youtu.be/zZ6vybT1HQs?si=RhpOgwgO6PPEWZtl',
        img: 'PHP Full Course for non-haters.webp',
        date: '2023-03-29',
        tags: [VideoTag.All],
    },
    {
        title: 'API Platform Conference 2023 - Nicolas Grekas - Developing APIs with Symfony in 2023',
        link: 'https://youtu.be/g6Q65q4QAD0?si=JwmFWHu336OJw2kL',
        img: 'API Platform Conference 2023 - Nicolas Grekas - Developing APIs with Symfony in 2023.webp',
        date: '2023-12-01',
        tags: [VideoTag.All, VideoTag.Symfony],
    },
    {
        title: 'Request and Response with Symfony and beyond | A simple guide',
        link: 'https://youtu.be/5EaOI1ZQi50?si=-ce6dClqxzgsGjIH',
        img: 'Request and Response with Symfony and beyond A simple guide.webp',
        date: '2024-06-11',
        tags: [VideoTag.All, VideoTag.Symfony],
    },
    {
        title: 'Symfony 7 - Emailing',
        link: 'https://youtu.be/xLxc505aYog?si=W4EA0cSSxOWYllap',
        img: 'Symfony 7 - Emailing.webp',
        date: '2024-04-03',
        tags: [VideoTag.All, VideoTag.Symfony],
    },
])

export default recommendedVideos
