name: GitHub Actions

on:
    push:
        branches: ['master']
    pull_request:
        branches: ['master']

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: '24.x'

            - name: Build
              run: |
                  npm i
                  npm run prod

            - name: Test
              run: npm test
